/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/JSP_Servlet/Servlet.java to edit this template
 */
package com.attendance.servlet;

import com.attendance.common.SessionUtils;
import com.attendance.connections.DBConnection;
import com.attendance.dbutils.AttendanceReportDBUtils;
import com.attendance.dto.Attendance;
import com.attendance.dto.User;
import com.itextpdf.text.BaseColor;
import com.itextpdf.text.Chunk;
import com.itextpdf.text.Document;
import com.itextpdf.text.Element;
import com.itextpdf.text.Font;
import com.itextpdf.text.PageSize;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.Phrase;
import com.itextpdf.text.pdf.PdfPCell;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import java.io.IOException;
import java.io.PrintWriter;
import jakarta.servlet.ServletException;
import jakarta.servlet.http.HttpServlet;
import jakarta.servlet.http.HttpServletRequest;
import jakarta.servlet.http.HttpServletResponse;
import jakarta.servlet.http.HttpSession;
import java.sql.Connection;
import java.util.List;

/**
 *
 * @author vaishnavi.dhole
 */
public class AttendanceReportPdfServlet extends HttpServlet {

   @Override
    protected void doGet(HttpServletRequest request, HttpServletResponse response)
            throws ServletException, IOException {

        HttpSession session = request.getSession(false);
        User login = SessionUtils.getLoginedUser(session);

        if (login == null) {
            response.sendRedirect(request.getContextPath() + "/index.jsp");
            return;
        }

        String startDate = request.getParameter("startDate");
        String endDate = request.getParameter("endDate");

        int siteId = 0;
        if (request.getParameter("siteId") != null && !request.getParameter("siteId").isEmpty()) {
            siteId = Integer.parseInt(request.getParameter("siteId"));
        }

        if (!"ADMIN".equals(login.getRole())) {
            siteId = login.getSiteId();
        }

        response.setContentType("application/pdf");
        response.setHeader("Content-Disposition", "attachment; filename=attendance_report.pdf");

        try (Connection conn = DBConnection.PGConnection()) {

            List<Attendance> list =
                    AttendanceReportDBUtils.getAttendanceReport(conn, startDate, endDate, siteId, login.getRole());

            Document document = new Document(PageSize.A4.rotate(), 20, 20, 20, 20);
            PdfWriter.getInstance(document, response.getOutputStream());

            document.open();

            Font titleFont = new Font(Font.FontFamily.HELVETICA, 16, Font.BOLD);
            Font headerFont = new Font(Font.FontFamily.HELVETICA, 11, Font.BOLD, BaseColor.WHITE);
            Font normalFont = new Font(Font.FontFamily.HELVETICA, 10);

            Paragraph title = new Paragraph("Attendance Report", titleFont);
            title.setAlignment(Element.ALIGN_CENTER);
            document.add(title);

            document.add(new Paragraph("From: " + startDate + "   To: " + endDate, normalFont));
            document.add(new Paragraph("Generated By: " + login.getFullName(), normalFont));
            document.add(Chunk.NEWLINE);

            PdfPTable table = new PdfPTable(7);
            table.setWidthPercentage(100);
            table.setWidths(new float[]{2f, 4f, 3f, 2f, 2f, 3f, 2f});

            addHeaderCell(table, "Date", headerFont);
            addHeaderCell(table, "Worker", headerFont);
            addHeaderCell(table, "Work Type", headerFont);
            addHeaderCell(table, "Day Type", headerFont);
            addHeaderCell(table, "Wage", headerFont);
            addHeaderCell(table, "Supervisor", headerFont);
            addHeaderCell(table, "Photo", headerFont);

            double totalWage = 0;

            for (Attendance a : list) {

                table.addCell(new PdfPCell(new Phrase(a.getAttendanceDate(), normalFont)));
                table.addCell(new PdfPCell(new Phrase(a.getWorkerName(), normalFont)));
                table.addCell(new PdfPCell(new Phrase(a.getWorkTypeName(), normalFont)));
                table.addCell(new PdfPCell(new Phrase(a.getDayType(), normalFont)));
                table.addCell(new PdfPCell(new Phrase("₹ " + a.getWage(), normalFont)));
                table.addCell(new PdfPCell(new Phrase(a.getSupervisorName(), normalFont)));
                table.addCell(new PdfPCell(new Phrase("View", normalFont)));

                totalWage += a.getWage();
            }

            document.add(table);
            document.add(Chunk.NEWLINE);

            Paragraph total = new Paragraph("Total Wage: ₹ " + totalWage, titleFont);
            total.setAlignment(Element.ALIGN_RIGHT);
            document.add(total);

            document.close();

        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private void addHeaderCell(PdfPTable table, String text, Font font) {
        PdfPCell cell = new PdfPCell(new Phrase(text, font));
        cell.setBackgroundColor(new BaseColor(60, 60, 60));
        cell.setHorizontalAlignment(Element.ALIGN_CENTER);
        cell.setPadding(6);
        table.addCell(cell);
    }
}