/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/JSP_Servlet/Servlet.java to edit this template
 */
package com.attendance.servlet;

import com.attendance.common.SessionUtils;
import com.attendance.connections.DBConnection;
import com.attendance.dbutils.PaymentReportDBUtils;
import com.attendance.dto.Payment;
import com.attendance.dto.User;
import com.itextpdf.text.BaseColor;
import com.itextpdf.text.Chunk;
import com.itextpdf.text.Document;
import com.itextpdf.text.Element;
import com.itextpdf.text.Font;
import com.itextpdf.text.PageSize;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.Phrase;
import com.itextpdf.text.pdf.PdfPCell;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import java.io.IOException;
import java.io.PrintWriter;
import jakarta.servlet.ServletException;
import jakarta.servlet.http.HttpServlet;
import jakarta.servlet.http.HttpServletRequest;
import jakarta.servlet.http.HttpServletResponse;
import jakarta.servlet.http.HttpSession;
import java.sql.Connection;
import java.util.List;

/**
 *
 * @author vaishnavi.dhole
 */
public class PaymentReportPdfServlet extends HttpServlet {

    @Override
    protected void doGet(HttpServletRequest request, HttpServletResponse response)
            throws ServletException, IOException {

        HttpSession session = request.getSession(false);
        User login = SessionUtils.getLoginedUser(session);

        if (login == null) {
            response.sendRedirect(request.getContextPath() + "/index.jsp");
            return;
        }

        String startDate = request.getParameter("startDate");
        String endDate = request.getParameter("endDate");

        int siteId = login.getSiteId();

        response.setContentType("application/pdf");
        response.setHeader("Content-Disposition", "attachment; filename=payment_report.pdf");

        try (Connection conn = DBConnection.PGConnection()) {

            List<Payment> list = PaymentReportDBUtils.paymentReport(conn, startDate, endDate, siteId, login.getRole());

            Document document = new Document(PageSize.A4.rotate(), 20, 20, 20, 20);
            PdfWriter.getInstance(document, response.getOutputStream());

            document.open();

            Font titleFont = new Font(Font.FontFamily.HELVETICA, 16, Font.BOLD);
            Font headerFont = new Font(Font.FontFamily.HELVETICA, 11, Font.BOLD, BaseColor.WHITE);
            Font normalFont = new Font(Font.FontFamily.HELVETICA, 10);

            Paragraph title = new Paragraph("Payment Report", titleFont);
            title.setAlignment(Element.ALIGN_CENTER);
            document.add(title);

            document.add(new Paragraph("From: " + startDate + " To: " + endDate, normalFont));
            document.add(new Paragraph("Generated By: " + login.getFullName(), normalFont));
            document.add(Chunk.NEWLINE);

            PdfPTable table = new PdfPTable(8);
            table.setWidthPercentage(100);

            addHeader(table, "Date", headerFont);
            addHeader(table, "Worker", headerFont);
            addHeader(table, "Site", headerFont);
            addHeader(table, "Amount", headerFont);
            addHeader(table, "Mode", headerFont);
            addHeader(table, "Reference", headerFont);
            addHeader(table, "Notes", headerFont);
            addHeader(table, "Recorded By", headerFont);

            double total = 0;

            for (Payment p : list) {
                table.addCell(new PdfPCell(new Phrase(p.getPaymentDate(), normalFont)));
                table.addCell(new PdfPCell(new Phrase(p.getWorkerName(), normalFont)));
                table.addCell(new PdfPCell(new Phrase(p.getSiteName(), normalFont)));
                table.addCell(new PdfPCell(new Phrase("₹ " + p.getAmount(), normalFont)));
                table.addCell(new PdfPCell(new Phrase(p.getPaymentMode(), normalFont)));
                table.addCell(new PdfPCell(new Phrase(p.getReferenceNumber(), normalFont)));
                table.addCell(new PdfPCell(new Phrase(p.getNotes(), normalFont)));
                table.addCell(new PdfPCell(new Phrase(p.getRecordedByName(), normalFont)));

                total += p.getAmount();
            }

            document.add(table);

            document.add(Chunk.NEWLINE);

            Paragraph totalText = new Paragraph("Total Paid: ₹ " + total, titleFont);
            totalText.setAlignment(Element.ALIGN_RIGHT);
            document.add(totalText);

            document.close();

        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private void addHeader(PdfPTable table, String text, Font font) {
        PdfPCell cell = new PdfPCell(new Phrase(text, font));
        cell.setBackgroundColor(new BaseColor(50, 50, 50));
        cell.setPadding(6);
        cell.setHorizontalAlignment(Element.ALIGN_CENTER);
        table.addCell(cell);
    }
}
